# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

# AJOUT DES SEEDS

puts "Cleaning database..."
Booking.destroy_all
Offer.destroy_all
User.destroy_all

puts 'Creating 2 fake users...'

user1 = User.create(first_name: "John", last_name: "Smith", email: 'jsmith@gmail.com', password: '123456')
user2 = User.create(first_name: "Fred", last_name: "Mercury", email: 'fmercury@gmail.com', password: '123456')

puts 'Creating 15 fake offers...'
category = ["kitesurf", "paddle", "planche à voile","planche de surf", "Vélo", "roller", "ski", "snowboard", "skateboard", "raquette de tennis"]
cities = ["Paris", "Marseille", "Lyon", "Lille", "Rouen", "Bordeaux", "Strasbourg", "Rennes", "Montpellier", "Nantes", "Angers"]

Offer.create(user: user1, title: "Kite surf pack complet", description: "Je loue mon kite surf. Le matériel est complet, il contient: une planche 150 cm / 42 cm Fanatic, les barres, l'aile 13m2 Trust, le gonfleur, un leash", price: 50, location: "Hyères", picture_url: "https://www.thecornershop.fr/modules/wbimgoffer/views/img/f4c2efdbc4e22283f0c73dfb40e117ef81d63cb0_pack-reedin-2022.jpg,https://www.gong-galaxy.com/wp-content/uploads/2023/01/12_1500-221220-GONGKITE-CATCH-00017-768x512.jpg,https://www.kitemana.fr/_images/h537/reedin-kiteboarding-kevpro-2021-kiteboard-287557.jpg,https://www.fun-diffusion.com/3961-thickbox_default/pompe-gonflage-aile-wing-wingfoil-duotone-manometre.jpg", sport_category: "kitesurf")
Offer.create(user: user1, title: "Vélo électrique", description: "Bonjour, je vous propose mon vélo électrique en location à la journée. Il a une autonomie d'à peu près 30km lorsqu'il est utilisé au maximum de l'aide électrique. Les pneus sont neufs et les freins en bon état, il tient bien la route mais n'est pas fait pour le tout terrain. Loué avec un U et le chargeur de batterie en cas de location de plus d'une journée. Une caution de 100 euros sera demandée, qui sera rendue à la fin de la location même si pneus crevé.", price: 25, location: "Paris", picture_url: "https://www.velo-electrique-rennes.fr/images/l700/5723.jpg,https://www.veloactif.com/media/catalog/product/cache/1/thumbnail/625x400/9df78eab33525d08d6e5fb8d27136e95/w/i/winora-my21-detail-front-sinus-9-darkslategrey.jpg,https://www.veloactif.com/media/catalog/product/cache/1/thumbnail/625x400/9df78eab33525d08d6e5fb8d27136e95/w/i/winora-my21-detail-motor-sinus-9-darkslategrey.jpg,https://cdn.lesnumeriques.com/optim/test/18/184785/302ca26d-winora-sinus-9-un-velo-electrique-urbain-confortable-et-bien-equipe__1200_1200__1039-84-3739-2784.jpeg", sport_category: "vélo")
Offer.create(user: user1, title: "Location ski", description: "Hello, Je loue paire de ski 169cm pour un jour le week-end ou la semaine. C'est des skis plutôt orientés piste, ultra maniable. Ils sont loués avec bâton mais sans chaussure", price: 15, location: "Lyon", picture_url: "https://i.ebayimg.com/images/g/N1oAAOSwI3hjGfD3/s-l1600.jpg,https://cdn.shopify.com/s/files/1/0040/1919/1878/products/57_f468fa72-2681-4a5c-b16f-40a7e1b9604c_1024x1024.jpg?v=1662707631,https://cdn.shopify.com/s/files/1/0040/1919/1878/products/57_6e714a4c-6619-43ba-81f5-bdb40bda95a3_1024x1024.jpg?v=1662707638,https://cdn.shopify.com/s/files/1/0040/1919/1878/products/57_45e82409-f88d-42e3-aa92-d5a9f2bba0dd_1024x1024.jpg?v=1662707640", sport_category: "ski")
Offer.create(user: user2, title: "Raquette de tennis WILSON Federer", description: "Location à la journée de ma raquette de tennis, modèle Wilson Federer", price: 5, location: "Lille", picture_url: "https://www.tenniscourt.fr/wp-content/uploads/2018/07/Federer-vraie-raquette.jpg,https://www.sportsystem.fr/59681-large_default/pro-staff-97uls.jpg,https://www.extreme-tennis.fr/17364-medium_default/raquette-wilson-pro-staff-rf97-autograph-v130-340g.jpg,https://www.tenniscourt.fr/wp-content/uploads/2018/07/Raquette-Federer.jpg", sport_category: "raquette de tennis")
Offer.create(user: user2, title: category.sample, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ut fringilla neque. Sed fringilla vitae mi in malesuada. Integer vulputate arcu et arcu porttitor viverra.", price: rand(15..100), location: cities.sample, picture_url: "https://loremflickr.com/640/480/sports,https://loremflickr.com/640/480/sports,https://loremflickr.com/640/480/sports,https://loremflickr.com/640/480/sports", sport_category: category.sample)
Offer.create(user: user2, title: category.sample, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ut fringilla neque. Sed fringilla vitae mi in malesuada. Integer vulputate arcu et arcu porttitor viverra.", price: rand(15..100), location: cities.sample, picture_url: "https://loremflickr.com/640/480/sports,https://loremflickr.com/640/480/sports,https://loremflickr.com/640/480/sports,https://loremflickr.com/640/480/sports", sport_category: category.sample)
Offer.create(user: user2, title: category.sample, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ut fringilla neque. Sed fringilla vitae mi in malesuada. Integer vulputate arcu et arcu porttitor viverra.", price: rand(15..100), location: cities.sample, picture_url: "https://loremflickr.com/640/480/sports,https://loremflickr.com/640/480/sports,https://loremflickr.com/640/480/sports,https://loremflickr.com/640/480/sports", sport_category: category.sample)
Offer.create(user: user2, title: category.sample, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ut fringilla neque. Sed fringilla vitae mi in malesuada. Integer vulputate arcu et arcu porttitor viverra.", price: rand(15..100), location: cities.sample, picture_url: "https://loremflickr.com/640/480/sports,https://loremflickr.com/640/480/sports,https://loremflickr.com/640/480/sports,https://loremflickr.com/640/480/sports", sport_category: category.sample)
Offer.create(user: user2, title: category.sample, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ut fringilla neque. Sed fringilla vitae mi in malesuada. Integer vulputate arcu et arcu porttitor viverra.", price: rand(15..100), location: cities.sample, picture_url: "https://loremflickr.com/640/480/sports,https://loremflickr.com/640/480/sports,https://loremflickr.com/640/480/sports,https://loremflickr.com/640/480/sports", sport_category: category.sample)
Offer.create(user: user2, title: category.sample, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ut fringilla neque. Sed fringilla vitae mi in malesuada. Integer vulputate arcu et arcu porttitor viverra.", price: rand(15..100), location: cities.sample, picture_url: "https://loremflickr.com/640/480/sports,https://loremflickr.com/640/480/sports,https://loremflickr.com/640/480/sports,https://loremflickr.com/640/480/sports", sport_category: category.sample)
Offer.create(user: user1, title: category.sample, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ut fringilla neque. Sed fringilla vitae mi in malesuada. Integer vulputate arcu et arcu porttitor viverra.", price: rand(15..100), location: cities.sample, picture_url: "https://loremflickr.com/640/480/sports,https://loremflickr.com/640/480/sports,https://loremflickr.com/640/480/sports,https://loremflickr.com/640/480/sports", sport_category: category.sample)
Offer.create(user: user1, title: category.sample, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ut fringilla neque. Sed fringilla vitae mi in malesuada. Integer vulputate arcu et arcu porttitor viverra.", price: rand(15..100), location: cities.sample, picture_url: "https://loremflickr.com/640/480/sports,https://loremflickr.com/640/480/sports,https://loremflickr.com/640/480/sports,https://loremflickr.com/640/480/sports", sport_category: category.sample)
Offer.create(user: user1, title: category.sample, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ut fringilla neque. Sed fringilla vitae mi in malesuada. Integer vulputate arcu et arcu porttitor viverra.", price: rand(15..100), location: cities.sample, picture_url: "https://loremflickr.com/640/480/sports,https://loremflickr.com/640/480/sports,https://loremflickr.com/640/480/sports,https://loremflickr.com/640/480/sports", sport_category: category.sample)
Offer.create(user: user1, title: category.sample, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ut fringilla neque. Sed fringilla vitae mi in malesuada. Integer vulputate arcu et arcu porttitor viverra.", price: rand(15..100), location: cities.sample, picture_url: "https://loremflickr.com/640/480/sports,https://loremflickr.com/640/480/sports,https://loremflickr.com/640/480/sports,https://loremflickr.com/640/480/sports", sport_category: category.sample)
Offer.create(user: user1, title: category.sample, description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque ut fringilla neque. Sed fringilla vitae mi in malesuada. Integer vulputate arcu et arcu porttitor viverra.", price: rand(15..100), location: cities.sample, picture_url: "https://loremflickr.com/640/480/sports,https://loremflickr.com/640/480/sports,https://loremflickr.com/640/480/sports,https://loremflickr.com/640/480/sports", sport_category: category.sample)


puts 'Finished!'
