# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)

# AJOUT DES SEEDS

puts "Cleaning database..."
Booking.destroy_all
Offer.destroy_all
User.destroy_all

puts 'Creating 2 fake users...'

user1 = User.create(first_name: "John", last_name: "Smith", email: 'jsmith@gmail.com', password: '123456')
user2 = User.create(first_name: "Fred", last_name: "Mercury", email: 'fmercury@gmail.com', password: '123456')

puts 'Creating 17 fake offers...'

Offer.create(user: user1, title: "Kite surf pack complet", description: "Je loue mon kite surf. Le matériel est complet, il contient: une planche 150 cm / 42 cm Fanatic, les barres, l'aile 13m2 Trust, le gonfleur, un leash", price: 50, location: "Hyères", picture_seed: "https://www.thecornershop.fr/modules/wbimgoffer/views/img/f4c2efdbc4e22283f0c73dfb40e117ef81d63cb0_pack-reedin-2022.jpg,https://www.gong-galaxy.com/wp-content/uploads/2023/01/12_1500-221220-GONGKITE-CATCH-00017-768x512.jpg,https://www.kitemana.fr/_images/h537/reedin-kiteboarding-kevpro-2021-kiteboard-287557.jpg,https://www.fun-diffusion.com/3961-thickbox_default/pompe-gonflage-aile-wing-wingfoil-duotone-manometre.jpg", sport_category: "kitesurf")
Offer.create(user: user1, title: "Vélo électrique", description: "Bonjour, je vous propose mon vélo électrique en location à la journée. Il a une autonomie d'à peu près 30km lorsqu'il est utilisé au maximum de l'aide électrique. Les pneus sont neufs et les freins en bon état, il tient bien la route mais n'est pas fait pour le tout terrain. Loué avec un U et le chargeur de batterie en cas de location de plus d'une journée. Une caution de 100 euros sera demandée, qui sera rendue à la fin de la location même si pneus crevé.", price: 25, location: "Paris", picture_seed: "https://www.velo-electrique-rennes.fr/images/l700/5723.jpg,https://www.veloactif.com/media/catalog/product/cache/1/thumbnail/625x400/9df78eab33525d08d6e5fb8d27136e95/w/i/winora-my21-detail-front-sinus-9-darkslategrey.jpg,https://www.veloactif.com/media/catalog/product/cache/1/thumbnail/625x400/9df78eab33525d08d6e5fb8d27136e95/w/i/winora-my21-detail-motor-sinus-9-darkslategrey.jpg,https://cdn.lesnumeriques.com/optim/test/18/184785/302ca26d-winora-sinus-9-un-velo-electrique-urbain-confortable-et-bien-equipe__1200_1200__1039-84-3739-2784.jpeg", sport_category: "vélo")
Offer.create(user: user1, title: "Location ski", description: "Hello, Je loue paire de ski 169cm pour un jour le week-end ou la semaine. C'est des skis plutôt orientés piste, ultra maniable. Ils sont loués avec bâton mais sans chaussure", price: 15, location: "Lyon", picture_seed: "https://i.ebayimg.com/images/g/N1oAAOSwI3hjGfD3/s-l1600.jpg,https://cdn.shopify.com/s/files/1/0040/1919/1878/products/57_f468fa72-2681-4a5c-b16f-40a7e1b9604c_1024x1024.jpg?v=1662707631,https://cdn.shopify.com/s/files/1/0040/1919/1878/products/57_6e714a4c-6619-43ba-81f5-bdb40bda95a3_1024x1024.jpg?v=1662707638,https://cdn.shopify.com/s/files/1/0040/1919/1878/products/57_45e82409-f88d-42e3-aa92-d5a9f2bba0dd_1024x1024.jpg?v=1662707640", sport_category: "ski")
Offer.create(user: user2, title: "Raquette de tennis WILSON Federer", description: "Location à la journée de ma raquette de tennis, modèle Wilson Federer", price: 5, location: "Lille", picture_seed: "https://www.tenniscourt.fr/wp-content/uploads/2018/07/Federer-vraie-raquette.jpg,https://www.sportsystem.fr/59681-large_default/pro-staff-97uls.jpg,https://www.extreme-tennis.fr/17364-medium_default/raquette-wilson-pro-staff-rf97-autograph-v130-340g.jpg,https://www.tenniscourt.fr/wp-content/uploads/2018/07/Raquette-Federer.jpg", sport_category: "raquette de tennis")
Offer.create(user: user2, title: "Planche à voile", description: "Location à la journée de ma planche à voile Tahe Techno Derive", price: 15, location: "Wissant", picture_seed: "https://www.windmag.com/media/guide_matos/2022/planches/tahe_techno_160d_2022.jpg,https://cdn1.neway-nantes.fr/9973-large_default/planche-160l-tahe-techno-derive-2021.jpg,https://www.marconyachting.com/1733-medium_default/tahe-techno-185d.jpg,image.png", sport_category: "planche à voile")
Offer.create(user: user2, title: "Planche de surf", description: "Location ma planche de surf à la journée + materiel. Vous pourrez profiter du matériel, planche de surf et combinaison, le temps d’une journée complète.", price: 10, location: "Biarritz", picture_seed: "https://contents.mediadecathlon.com/p1740706/k$1160fd349cadcdb913900d161f9edbfe/sq/surf-mousse-500-86-livre-avec-1-leash-et-3-ailerons.jpg?format=auto&f=969x969,https://contents.mediadecathlon.com/p1740713/k$6cb9dbf7abe8671a9f66cd3b76ebb3cf/sq/surf-mousse-500-86-livre-avec-1-leash-et-3-ailerons.jpg?format=auto&f=969x969,https://contents.mediadecathlon.com/p1758426/k$aef1871bd40edc6007cf1a85cd0d43e1/sq/surf-mousse-500-86-livre-avec-1-leash-et-3-ailerons.jpg?format=auto&f=969x969,https://surf-community.fr/wp-content/uploads/2017/05/Softech_Planche_Mousse-e1599643715168.jpg", sport_category: "planche de surf")
Offer.create(user: user2, title: "Paddle", description: "Location ma planche de padle à la journée + materiel. Vous pourrez profiter du matériel, planche de padle et de ma combinaison, le temps d’une journée complète.", price: 15, location: "Vannes", picture_seed: "https://www.standup-paddle.fr/wp-content/uploads/2020/04/femme-gym-paddle-1024x683.jpg,https://img.freepik.com/photos-premium/planche-surf-blanche-plage-sable-cours-stand-up-paddle-magnifique-paysage-tropical-insulaire-palmiers-sable-blanc-plage-concept-sports-nautiques_431724-1145.jpg,https://www.paddlegonflable.fr/wp-content/uploads/2020/11/paddle-spot.png,https://www.vidaxl.fr/dw/image/v2/BFNS_PRD/on/demandware.static/-/Sites-vidaxl-catalog-master-sku/default/dw36878a2d/hi-res/988/1011/499811/1143/6288/90632/image_4_90632.jpg?sw=400", sport_category: "paddle")
Offer.create(user: user2, title: "Location de mes rollers", description: "Location à la journée de mes rollers", price: 5, location: "Meaux", picture_seed: "https://m.media-amazon.com/images/I/71AnLvWZ6yL._AC_SX425_.jpg,https://m.media-amazon.com/images/I/71OthLfNmlL._AC_SX569_.jpg,https://www.cdiscount.com/pdt2/3/8/2/1/700x700/mp53742382/rw/roller-enfant-filles-et-garcons-roller-quad-enfan.jpg,https://m.media-amazon.com/images/I/81JK0x7f0HL._AC_SX425_.jpg", sport_category: "roller")
Offer.create(user: user2, title: "Je loue mom skate", description: "Location à la journée de mon skateboard", price: 7, location: "Paris", picture_seed: "https://upload.wikimedia.org/wikipedia/commons/4/41/Globe_Skateboard.jpg,https://pro.atelierenfant.com/img/anniversaire-skateboard-5-15-ans-paris-14e-10639.png,https://m3.onrangetout.com/10381-thickbox_default/crochet-de-rangement-pour-skateboard.jpghttps://img.20mn.fr/nwlISK_qRPi2jZhkVFUDMw/1200x768_illustration-personne-roulant-skateboard", sport_category: "skateboard")
Offer.create(user: user2, title: "Location de mon snow", description: "Location à la journée ou a la semaine de mon snowboard, modèle agressif 2000 idéale pour les confirmés ! Location avec chaussures envisageable, taille 44.", price: 15, location: "Chamonix", picture_seed: "https://sportydeal.com/storage/files/fr/22999/thumb-510x287.5/Snowboard-suisse-nidecker-elle-143-occasion-1676651906-1.jpeg,https://sportydeal.com/storage/files/fr/22999/thumb-510x287.5/Snowboard-suisse-nidecker-elle-143-occasion-1676651906-2.jpeg,https://sportydeal.com/storage/files/fr/22999/thumb-510x287.5/Snowboard-suisse-nidecker-elle-143-occasion-1676651907-5.jpeg,https://sportydeal.com/storage/files/fr/22999/thumb-510x287.5/Snowboard-suisse-nidecker-elle-143-occasion-1676651906-4.jpeg", sport_category: "snowboard")
Offer.create(user: user2, title: "Location de ma raquette", description: "Location de raquettes de tennis. Moins cher si location de plusieurs rasuettes ou pour le mois.", price: 7, location: "Paris", picture_seed: "https://www.extreme-tennis.fr/modules/prestatemplatev2/page-builder/wp-content/uploads/taille-1.jpg,https://www.sportsystem.fr/59924/wilson-ultra-100-v30.jpg,https://s3.eu-west-3.amazonaws.com/forums-tennis-classim-net/uploads/monthly_2020_04/3.jpg.4ad6674faf1631bc0211378ce8f51296.jpg,https://s3.eu-west-3.amazonaws.com/forums-tennis-classim-net/uploads/monthly_2020_04/2.jpg.a40a47219e3e2852a87c983ae2d618bb.jpg", sport_category: "raquette de tennis")
Offer.create(user: user2, title: "Rollers", description: "Je loue mes rollers taille 38 Roller powerslide Roller polyvalent pour de la randonnée ou des ballades en ville. Convient aux débutants et niveau intermédiaire.", price: 3, location: "Paris", picture_seed: "https://www.nomadeshop.com/100819-large_default/powerslide-roller-freeskate-next-core-black-100-noir.jpg,https://www.rollernco.com/29892-home_default/next-core-black-80-powerslide.jpg,https://www.tradeinn.com/f/13784/137848301_17/powerslide-patins-a-roues-alignees-next-core-80.jpg,https://cdn.skatepro.com/product/440/powerslide-next-core-black-100-freeskates-ml.jpg", sport_category: "roller")
Offer.create(user: user2, title: "Planche à voile en loc S/J/H", description: "Location à la semaine, journée ou à l'heure de ma planche à voile. Prix attractifs et senssations garanties.", price: 20, location: "Marseille", picture_seed: "https://chinookleucate.files.wordpress.com/2010/03/sany0048.jpg,https://chinookleucate.files.wordpress.com/2010/03/sany0038.jpg,https://chinookleucate.files.wordpress.com/2010/03/sany0046.jpg,https://chinookleucate.files.wordpress.com/2010/03/sany0049.jpg", sport_category: "planche à voile")
Offer.create(user: user2, title: "Materiel de kitesurf complet", description: "Location à la semaine de mon materiel complet de kitesurf. Materiel idéal pour débutants et confirmés, souahitant progresser de manière autonome. Possibilité de louer sur plusieurs semaines consécutives, prix dégréssif.", price: 15, location: "Hyères", picture_seed: "https://www.thecornershop.fr/34828-large_default/pack-complet-naish-ride-12m.jpg,https://www.thecornershop.fr/34829-large_default/pack-complet-naish-ride-12m.jpg,https://www.thecornershop.fr/34830-large_default/pack-complet-naish-ride-12m.jpg,https://tiki-center.com/wp-content/uploads/2021/06/IMG-20210403-WA0059-800x464.jpg", sport_category: "kitesurf")
Offer.create(user: user2, title: "Snowboard", description: "Prix négociable si vous le louez pour plusieurs jours Parfait pour homme ayant une taille comprise entre 175 et 190 cm. Planche très souple plutôt déstinée à un niveau intermédiaire/confimé (parfaite pour la piste et la poudreuse de bord de piste). Si vous êtes débutants elle a un bel avantage, c'est de permettre de faire des virages facilement donc vous pourrez progresser avec du bon matériel. Je peux vous louer des boots pointure 46 (5€) et des habits de montagne si nécessaire (manteau, gants, masque, pantalon, chaussettes, etc.)", price: 10, location: "La plagne", picture_seed: "https://static.everide.app/PSvoYWjg1kfdtI69XatYqV2mhjuAnDobLKpWwxyHt9w/rs:fill:602:698:1/q:75/g:ce/czM6Ly9zaXRlLWFwaS1pbWFnZXMvcHJvZHVjdGlvbi9wcm9kdWN0c1BpY3R1cmVzLzI1LTAyLTIwMjMvdS00ODk1NC9wLTAtMTY3NzM1MTM4OC1kNzI4OS5qcGc.jpg,https://www.intersportrent.com/IIC/Blog/Which%20snowboard%20size%20is%20right%20for%20me/image-thumb__25612__ir-2021-magazin-teaser/snowboard-113784_1920.jpeg,https://www.snowsurf.com/media/Publi-communiqu%C3%A9/glisshop/virage_carve.png,https://images.blue-tomato.com/is/image/bluetomato/304373067_style1.jpg-iBYhAiwEF2vnT5xk2UPmeFmPT3E/Dynasword+130+Snowboard.jpg?$m4$", sport_category: "snowboard")
Offer.create(user: user2, title: "Location de mon vélo de route Canyon", description: "Hello, je propose de louer mon vélo de route, de la marque Canyon, à la journée ou à la semaine. C'est un vélo idéal pour les sorties sur route. Taille de la potence : L", price: 12, location: "Rouen", picture_seed: "https://d1mgeijqpfaspl.cloudfront.net/uploads/bike/image_side/thumbs/1272/6300332d3a701_20220815_185603.jpg,https://images.ladepeche.fr/api/v1/images/view/5d09d5b6d286c24fa11cd745/large/image.jpg,https://cdn.road.cc/sites/default/files/styles/schema_org/public/valverde-movistar17_0.jpg,https://www.velonews.com/wp-content/uploads/2018/12/GettyImages-1051961278.jpg?width=728", sport_category: "Vélo")

puts 'Finished!'
